/**
 * MECHTWIN AI — In-Memory Relational Database & State Store
 * PostgreSQL-compatible entity repositories with ACID-like transactional operations
 * Tagline: "Engineering Intelligence for Every Machine."
 * Created & Engineered by Samil Khan
 */

import {
  Machine,
  User,
  Organization,
  Sensor,
  SensorReading,
  MaintenanceRecord,
  FaultPrediction,
  AnomalyEvent,
  Alert,
  SimulationRun,
  AuditLog,
  HistoricalDataPoint,
  MachineOperatingProfile,
} from '../../src/types';
import { HISTORICAL_30_DAYS } from '../../src/data/history30Days';

// 1. Initial Pre-Seeded Organizations
export const ORGANIZATIONS: Organization[] = [
  {
    id: 'ORG-001',
    name: 'Advanced Industrial Manufacturing Corp',
    industry: 'Turbomachinery & Heavy Process Engineering',
    siteLocation: 'Plant Unit 4 - Houston Energy Corridor, TX',
    licenseTier: 'Enterprise Industry 4.0',
    activeMachineCount: 3,
  },
];

// 2. Initial Pre-Seeded Users with Role-Based Access Control (RBAC)
export const USERS: User[] = [
  {
    id: 'USR-ADMIN-01',
    name: 'Samil Khan',
    email: 'samil.khan@mechtwin.ai',
    role: 'ADMIN',
    organizationId: 'ORG-001',
    organizationName: 'Advanced Industrial Manufacturing Corp',
    department: 'Principal Reliability Engineering & AI Architecture',
    avatarInitials: 'SK',
  },
  {
    id: 'USR-ENG-02',
    name: 'Marcus Vance',
    email: 'marcus.vance@industry.corp',
    role: 'ENGINEER',
    organizationId: 'ORG-001',
    organizationName: 'Advanced Industrial Manufacturing Corp',
    department: 'Plant Vibration & Rotating Equipment',
    avatarInitials: 'MV',
  },
  {
    id: 'USR-VIEW-03',
    name: 'Elena Rostova',
    email: 'elena.rostova@operations.corp',
    role: 'VIEWER',
    organizationId: 'ORG-001',
    organizationName: 'Advanced Industrial Manufacturing Corp',
    department: 'Operations & Maintenance Monitoring',
    avatarInitials: 'ER',
  },
];

// 3. Initial Reference Machine MT-001 and Fleet
export const MACHINES: Machine[] = [
  {
    id: 'MT-001',
    name: 'Heavy-Duty Centrifugal Slurry Pump System',
    tag: 'PUMP-SLURRY-01A',
    type: 'Centrifugal Pump & Electric Motor Assembly',
    manufacturer: 'Flowserve / Grundfos Industrial',
    model: 'ISO-2858 Heavy-Process 100-65-200',
    serialNumber: 'FS-2024-8849-B',
    location: 'Process Bay 03 - Water Treatment Facility',
    installationDate: '2023-04-15',
    operatingHours: 14820,
    status: 'NORMAL',
    healthScore: 84,
    ratedPowerKW: 22.0,
    ratedRPM: 1480,
    ratedVoltageV: 400,
    ratedCurrentA: 41.5,
    ratedPressureBar: 16.0,
    ratedFlowLPM: 1200,
    ratedHeadMeters: 45.0,
    mtbfHours: 25000,
    energyCostPerKWh: 0.14,
    components: [
      {
        id: 'motor',
        name: 'Electric Motor (TEFC 3-Phase Induction)',
        type: 'motor',
        temperature: 68.2,
        vibration: 2.1,
        condition: 'NORMAL',
        estimatedLifeDays: 450,
        riskLevel: 'Low',
        operatingHours: 14820,
        lastInspected: '2024-06-10',
        material: 'Cast Iron Frame (IEC 180M), Copper Windings Class F',
        specifications: {
          'Rated Power': '22 kW',
          'Synchronous Speed': '1500 RPM',
          Poles: 4,
          Efficiency: 'IE3 Premium (93.0%)',
        },
        highlightColor: '#0284c7',
        position3D: [-2.2, 0, 0],
        dataTrust: 'LIVE_SENSOR',
      },
      {
        id: 'coupling',
        name: 'Flexible Elastomeric Jaw Coupling',
        type: 'coupling',
        temperature: 58.5,
        vibration: 2.8,
        condition: 'NORMAL',
        estimatedLifeDays: 290,
        riskLevel: 'Low',
        operatingHours: 14820,
        lastInspected: '2024-04-18',
        material: 'Forged Steel Hubs with Polyurethane Spider (Shore 98A)',
        specifications: {
          'Nominal Torque': '250 N·m',
          'Max Angular Misalignment': '1.0°',
          'Max Radial Offset': '0.3 mm',
        },
        highlightColor: '#06b6d4',
        position3D: [-0.4, 0, 0],
        dataTrust: 'LIVE_SENSOR',
      },
      {
        id: 'shaft',
        name: 'High-Tensile Precision Drive Shaft',
        type: 'shaft',
        temperature: 59.2,
        vibration: 2.3,
        condition: 'NORMAL',
        estimatedLifeDays: 720,
        riskLevel: 'Low',
        operatingHours: 14820,
        lastInspected: '2024-03-12',
        material: 'AISI 4140 Quenched & Tempered Alloy Steel',
        specifications: {
          'Shaft Diameter': '45.0 mm',
          'Runout Tolerance': '< 0.02 mm',
          'Torsional Yield': '650 MPa',
        },
        highlightColor: '#3b82f6',
        position3D: [0.3, 0, 0],
        dataTrust: 'CALCULATED',
      },
      {
        id: 'bearing_de',
        name: 'Drive-End Bearing 01 (DE Deep Groove)',
        type: 'bearing_de',
        temperature: 71.4,
        vibration: 3.4,
        condition: 'WARNING',
        estimatedLifeDays: 31,
        riskLevel: 'Medium',
        operatingHours: 14820,
        lastInspected: '2024-05-22',
        material: 'High-Carbon Chromium Steel (SKF 6208-2Z/C3)',
        specifications: {
          'Dynamic Load (C)': '32.5 kN',
          'Limiting Speed': '11000 RPM',
          'Defect Frequency (BPFO)': '105.8 Hz',
        },
        highlightColor: '#f59e0b',
        position3D: [-1.2, 0, 0],
        dataTrust: 'LIVE_SENSOR',
      },
      {
        id: 'bearing_nde',
        name: 'Non-Drive End Bearing 02 (NDE)',
        type: 'bearing_nde',
        temperature: 64.0,
        vibration: 1.8,
        condition: 'NORMAL',
        estimatedLifeDays: 380,
        riskLevel: 'Low',
        operatingHours: 14820,
        lastInspected: '2024-05-22',
        material: 'Deep Groove Ball Bearing (SKF 6206)',
        specifications: {
          'Dynamic Load (C)': '20.3 kN',
          'Limiting Speed': '14000 RPM',
        },
        highlightColor: '#10b981',
        position3D: [-3.1, 0, 0],
        dataTrust: 'LIVE_SENSOR',
      },
      {
        id: 'impeller',
        name: 'Centrifugal Pump (Enclosed 6-Vane Impeller & Volute)',
        type: 'impeller',
        temperature: 54.0,
        vibration: 2.2,
        condition: 'NORMAL',
        estimatedLifeDays: 310,
        riskLevel: 'Low',
        operatingHours: 14820,
        lastInspected: '2024-02-10',
        material: 'Stainless Steel CF8M (SS316) / Ductile Iron Volute',
        specifications: {
          'Impeller Diameter': '205 mm',
          'Specific Speed': '28 rpm·m³/s',
          'Balance Quality': 'ISO G2.5',
        },
        highlightColor: '#8b5cf6',
        position3D: [1.4, 0, 0],
        dataTrust: 'CALCULATED',
      },
      {
        id: 'pipe_outlet',
        name: 'Discharge Outlet Nozzle & Check Valve (DN80)',
        type: 'pipe_outlet',
        temperature: 32.0,
        vibration: 1.6,
        condition: 'NORMAL',
        estimatedLifeDays: 1200,
        riskLevel: 'Low',
        operatingHours: 14820,
        lastInspected: '2024-01-20',
        material: 'Carbon Steel ASTM A106 Grade B',
        specifications: {
          'Nominal Diameter': 'DN 80 (3")',
          'Discharge Velocity': '3.2 m/s',
        },
        highlightColor: '#0ea5e9',
        position3D: [1.4, 1.6, 0],
        dataTrust: 'LIVE_SENSOR',
      },
    ],
    sensors: [
      {
        id: 'SEN-T01',
        machineId: 'MT-001',
        componentId: 'bearing_de',
        name: 'DE Bearing Temperature PT100',
        type: 'temperature',
        unit: '°C',
        samplingRateHz: 10,
        status: 'ONLINE',
        calibrationStatus: 'CALIBRATED',
        minSafe: 20,
        maxSafe: 75,
        minWarning: 75,
        maxWarning: 90,
        lastReading: 68.2,
        lastSyncTimestamp: Date.now(),
        quality: 'GOOD',
        source: 'SIMULATED',
        dataTrust: 'LIVE_SENSOR',
        location: 'Drive-End Bearing Housing',
      },
      {
        id: 'SEN-V01',
        machineId: 'MT-001',
        componentId: 'bearing_de',
        name: 'Tri-Axial Accelerometer (DE)',
        type: 'vibration',
        unit: 'mm/s RMS',
        samplingRateHz: 2560,
        status: 'ONLINE',
        calibrationStatus: 'CALIBRATED',
        minSafe: 0.1,
        maxSafe: 2.3,
        minWarning: 2.3,
        maxWarning: 4.5,
        lastReading: 3.4,
        lastSyncTimestamp: Date.now(),
        quality: 'GOOD',
        source: 'SIMULATED',
        dataTrust: 'LIVE_SENSOR',
        location: 'Motor-Pump Flange DE',
      },
      {
        id: 'SEN-R01',
        machineId: 'MT-001',
        componentId: 'coupling',
        name: 'Optical Shaft Tachometer',
        type: 'rpm',
        unit: 'RPM',
        samplingRateHz: 50,
        status: 'ONLINE',
        calibrationStatus: 'CALIBRATED',
        minSafe: 1350,
        maxSafe: 1520,
        minWarning: 1300,
        maxWarning: 1550,
        lastReading: 1480,
        lastSyncTimestamp: Date.now(),
        quality: 'GOOD',
        source: 'SIMULATED',
        dataTrust: 'LIVE_SENSOR',
        location: 'Coupling Guard',
      },
      {
        id: 'SEN-I01',
        machineId: 'MT-001',
        componentId: 'motor',
        name: 'Current CT Transducer (Phase A/B/C)',
        type: 'current',
        unit: 'A',
        samplingRateHz: 100,
        status: 'ONLINE',
        calibrationStatus: 'CALIBRATED',
        minSafe: 15,
        maxSafe: 38,
        minWarning: 38,
        maxWarning: 44,
        lastReading: 34.8,
        lastSyncTimestamp: Date.now(),
        quality: 'GOOD',
        source: 'SIMULATED',
        dataTrust: 'LIVE_SENSOR',
        location: 'Motor Junction Box',
      },
      {
        id: 'SEN-P01',
        machineId: 'MT-001',
        componentId: 'motor',
        name: 'Active Power Meter (Modbus)',
        type: 'power',
        unit: 'kW',
        samplingRateHz: 10,
        status: 'ONLINE',
        calibrationStatus: 'CALIBRATED',
        minSafe: 5,
        maxSafe: 20,
        minWarning: 20,
        maxWarning: 23,
        lastReading: 17.6,
        lastSyncTimestamp: Date.now(),
        quality: 'GOOD',
        source: 'SIMULATED',
        dataTrust: 'CALCULATED',
        location: 'VFD Feeder Panel',
      },
      {
        id: 'SEN-PI01',
        machineId: 'MT-001',
        componentId: 'impeller',
        name: 'Piezoelectric Suction Pressure Transducer',
        type: 'pressure_inlet',
        unit: 'bar',
        samplingRateHz: 20,
        status: 'ONLINE',
        calibrationStatus: 'CALIBRATED',
        minSafe: 0.8,
        maxSafe: 3.0,
        minWarning: 0.5,
        maxWarning: 0.8,
        lastReading: 1.25,
        lastSyncTimestamp: Date.now(),
        quality: 'GOOD',
        source: 'SIMULATED',
        dataTrust: 'LIVE_SENSOR',
        location: 'Suction Spool Piece',
      },
      {
        id: 'SEN-PO01',
        machineId: 'MT-001',
        componentId: 'pipe_outlet',
        name: 'Discharge Pressure Transmitter',
        type: 'pressure_outlet',
        unit: 'bar',
        samplingRateHz: 20,
        status: 'ONLINE',
        calibrationStatus: 'CALIBRATED',
        minSafe: 3.5,
        maxSafe: 5.5,
        minWarning: 3.0,
        maxWarning: 6.0,
        lastReading: 4.65,
        lastSyncTimestamp: Date.now(),
        quality: 'GOOD',
        source: 'SIMULATED',
        dataTrust: 'LIVE_SENSOR',
        location: 'Discharge Check Valve',
      },
      {
        id: 'SEN-F01',
        machineId: 'MT-001',
        componentId: 'pipe_outlet',
        name: 'Electromagnetic Flow Meter',
        type: 'flow',
        unit: 'L/min',
        samplingRateHz: 5,
        status: 'ONLINE',
        calibrationStatus: 'CALIBRATED',
        minSafe: 800,
        maxSafe: 1400,
        minWarning: 600,
        maxWarning: 1500,
        lastReading: 1140,
        lastSyncTimestamp: Date.now(),
        quality: 'GOOD',
        source: 'SIMULATED',
        dataTrust: 'LIVE_SENSOR',
        location: 'Discharge Header',
      },
    ],
    latestTelemetry: {
      timestamp: Date.now(),
      temperature: 68.2,
      vibration: 3.4,
      vibrationPeak: 5.12,
      vibrationKurtosis: 3.85,
      rpm: 1480,
      current: 34.8,
      voltage: 400.2,
      power: 17.6,
      powerFactor: 0.88,
      pressureInlet: 1.25,
      pressureOutlet: 4.65,
      flowRate: 1140,
      torque: 113.5,
      efficiency: 87.4,
      healthScore: 84,
      failureProbability: 16,
      remainingUsefulLifeDays: 31,
      dataTrust: 'LIVE_SENSOR',
      quality: 'GOOD',
      source: 'SIMULATED',
    },
    healthBreakdown: {
      overallScore: 84,
      previousScore: 96,
      deltaReason:
        'Vibration velocity increased +14% (Zone B) and Drive-End thermal rise +9.4°C over baseline.',
      status: 'WARNING',
      factors: [
        {
          name: 'Vibration Velocity (ISO 10816-3)',
          weight: 0.35,
          value: '3.40 mm/s RMS',
          benchmark: '< 2.3 mm/s (Zone A)',
          score: 72,
          status: 'Degraded',
          impact: 9.8,
          description:
            'Operating in ISO Zone B/C boundary with elevated harmonic energy on Bearing 01.',
        },
        {
          name: 'Thermal Rise (IEC 60034-1)',
          weight: 0.25,
          value: '68.2 °C',
          benchmark: '< 75 °C',
          score: 88,
          status: 'Optimal',
          impact: 3.0,
          description:
            'Stator and housing temperature operating inside safe Class F thermal limit.',
        },
        {
          name: 'Bearing Kinematic Life (ISO 281)',
          weight: 0.2,
          value: '31 days RUL (Est)',
          benchmark: '> 90 days',
          score: 76,
          status: 'Degraded',
          impact: 4.8,
          description:
            'Dynamic micro-spall fatigue wear reducing predicted L10h rating life.',
        },
        {
          name: 'Operating Efficiency (BEP)',
          weight: 0.2,
          value: '87.4%',
          benchmark: '> 89.0%',
          score: 92,
          status: 'Optimal',
          impact: 1.6,
          description:
            'Pumping loop operating within 2.5% of Best Efficiency Point.',
        },
      ],
    },
    activeFaults: [
      {
        id: 'fault-001',
        machineId: 'MT-001',
        faultType: 'Bearing Wear',
        probability: 78,
        severity: 'HIGH',
        affectedComponent: 'Drive-End Bearing 01 (SKF 6208-2Z/C3)',
        componentId: 'bearing_de',
        evidence: [
          'Vibration RMS elevated to 3.40 mm/s (ISO 10816 Zone B boundary: 2.3 mm/s)',
          'Vibration Kurtosis increased to 3.85 indicating repetitive transient impacts',
          'Temperature increased by 9.4°C over steady-state baseline in past 72h',
          'Spectral peak detected at BPFO harmonic (105.8 Hz @ 1480 RPM)',
        ],
        recommendedAction:
          'Perform high-frequency demodulation analysis, replenish lithium-complex synthetic grease, and prepare replacement SKF 6208 bearing kit within 72 operating hours.',
        maintenancePriority: 'P2 - Within 48h',
        estimatedTimeToFailureHours: 144,
        detectedAt: new Date(Date.now() - 3600000 * 18).toISOString(),
        isoStandardRef: 'ISO 10816-3 Class II / ISO 15243',
        dataTrust: 'PREDICTED',
      },
    ],
  },
];

// 4. In-Memory Relational State Tables
class RelationalDatabase {
  public organizations: Organization[] = [...ORGANIZATIONS];
  public users: User[] = [...USERS];
  public machines: Machine[] = [...MACHINES];
  public history30Days: HistoricalDataPoint[] = [...HISTORICAL_30_DAYS];
  public maintenanceRecords: MaintenanceRecord[] = [
    {
      id: 'WO-2026-088',
      machineId: 'MT-001',
      machineName: 'Heavy-Duty Centrifugal Slurry Pump System',
      componentId: 'bearing_de',
      componentName: 'Drive-End Bearing 01 (SKF 6208-2Z/C3)',
      type: 'PREDICTIVE',
      issue: 'Elevated BPFO vibration harmonic & thermal rise on DE bearing',
      priority: 'HIGH',
      assignedEngineer: 'Marcus Vance',
      createdDate: '2026-08-14T08:30:00Z',
      dueDate: '2026-08-18T17:00:00Z',
      status: 'IN_PROGRESS',
      estimatedHours: 3.5,
      requiredParts: [
        'SKF 6208-2Z/C3 Deep Groove Ball Bearing',
        'Shell Gadus S2 V220 Synthetic Grease (400g)',
        'FKM Viton Shaft Seal 45x65x8mm',
      ],
      notes:
        'Triggered by automated MechTwin AI predictive diagnosis. Dial indicator and laser alignment tool required.',
    },
    {
      id: 'WO-2026-079',
      machineId: 'MT-001',
      machineName: 'Heavy-Duty Centrifugal Slurry Pump System',
      componentId: 'coupling',
      componentName: 'Flexible Elastomeric Jaw Coupling',
      type: 'PREVENTIVE',
      issue: 'Quarterly shaft alignment verification and spider elastomer inspection',
      priority: 'MEDIUM',
      assignedEngineer: 'Marcus Vance',
      createdDate: '2026-07-20T10:00:00Z',
      dueDate: '2026-07-22T16:00:00Z',
      completionDate: '2026-07-21T14:30:00Z',
      status: 'COMPLETED',
      estimatedHours: 2.0,
      actualHours: 1.75,
      requiredParts: ['Polyurethane Spider Insert Shore 98A (Red)'],
      notes:
        'Radial offset corrected from 0.18 mm to 0.03 mm. Angular misalignment within tolerance.',
    },
  ];
  public anomalyEvents: AnomalyEvent[] = [
    {
      id: 'ANOM-001',
      timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
      machineId: 'MT-001',
      machineName: 'Heavy-Duty Centrifugal Slurry Pump System',
      sensorId: 'SEN-V01',
      sensorType: 'vibration',
      severity: 'WARNING',
      observedValue: 3.4,
      expectedRange: [0.5, 2.3],
      unit: 'mm/s RMS',
      deviationPct: 47.8,
      possibleCause:
        'Outer ring bearing race micro-spalling or cyclic ball pass defect (BPFO)',
      acknowledged: false,
      dataTrust: 'CALCULATED',
    },
    {
      id: 'ANOM-002',
      timestamp: new Date(Date.now() - 3600000 * 5).toISOString(),
      machineId: 'MT-001',
      machineName: 'Heavy-Duty Centrifugal Slurry Pump System',
      sensorId: 'SEN-T01',
      sensorType: 'temperature',
      severity: 'INFO',
      observedValue: 68.2,
      expectedRange: [45.0, 65.0],
      unit: '°C',
      deviationPct: 4.9,
      possibleCause:
        'Sustained 92% plant throughput load combined with reduced lubricant film thickness',
      acknowledged: true,
      dataTrust: 'CALCULATED',
    },
  ];
  public alerts: Alert[] = [
    {
      id: 'ALT-001',
      timestamp: '15 minutes ago',
      machineId: 'MT-001',
      machineName: 'Heavy-Duty Centrifugal Slurry Pump System',
      sensorId: 'SEN-V01',
      level: 'WARNING',
      title: 'Elevated DE Bearing Vibration (Zone B Alert)',
      message:
        'Tri-axial accelerometer measured 3.40 mm/s RMS, exceeding ISO 10816-3 Zone A boundary (2.3 mm/s).',
      ruleTrigger: 'vibration_rms > 2.3 mm/s',
      value: '3.40 mm/s',
      threshold: '> 2.30 mm/s',
      acknowledged: false,
      resolved: false,
    },
    {
      id: 'ALT-002',
      timestamp: '52 minutes ago',
      machineId: 'MT-001',
      machineName: 'Heavy-Duty Centrifugal Slurry Pump System',
      sensorId: 'SEN-V01',
      level: 'INFO',
      title: 'Vibration Spectral Kurtosis Shift',
      message:
        'Statistical Kurtosis rose from 3.05 to 3.85, confirming non-Gaussian impulsive shock pulses from bearing raceway.',
      ruleTrigger: 'kurtosis > 3.50',
      value: '3.85 kurt',
      threshold: '> 3.50 kurt',
      acknowledged: true,
      resolved: false,
    },
  ];
  public simulationRuns: SimulationRun[] = [
    {
      id: 'SIM-RUN-01',
      timestamp: '2026-08-16T14:20:00Z',
      machineId: 'MT-001',
      machineName: 'Heavy-Duty Centrifugal Slurry Pump System',
      scenarioName: '110% VFD Overdrive Stress Scenario',
      inputs: {
        scenarioName: '110% VFD Overdrive',
        rpm: 1628,
        loadPercent: 100,
        suctionPressureBar: 1.25,
        ambientTempC: 32.0,
        lubricationDegradationPct: 20,
        operatingHoursOffset: 1000,
      },
      baseline: MACHINES[0].latestTelemetry,
      predicted: {
        powerKW: 24.2,
        temperatureC: 78.5,
        vibrationRMS: 4.65,
        efficiencyPct: 83.2,
        bearingLifeDays: 14,
        failureRiskPct: 82,
        estimatedAnnualCostUSD: 29640,
        riskAssessment:
          'HIGH RISK: Operating in ISO 10816 Zone C with thermal boundary lubrication failure risk.',
        recommendation:
          'Restrict continuous speed to 1480 RPM until DE bearing replacement is completed.',
        dataTrust: 'PREDICTED',
      },
      deltas: {
        powerDeltaKW: 6.6,
        tempDeltaC: 10.3,
        vibDeltaRMS: 1.25,
        effDeltaPct: -4.2,
        lifeDeltaDays: -17,
        costDeltaUSD: 8092,
      },
      createdBy: 'Samil Khan',
    },
  ];
  public auditLogs: AuditLog[] = [
    {
      id: 'AUD-001',
      timestamp: new Date(Date.now() - 3600000 * 1).toISOString(),
      userId: 'USR-ADMIN-01',
      userName: 'Samil Khan',
      role: 'ADMIN',
      action: 'WORK_ORDER_DISPATCHED',
      resourceType: 'MaintenanceRecord',
      resourceId: 'WO-2026-088',
      details: 'Created predictive maintenance work order for DE Bearing 01',
      status: 'SUCCESS',
      ipAddress: '192.168.10.45',
    },
    {
      id: 'AUD-002',
      timestamp: new Date(Date.now() - 3600000 * 3).toISOString(),
      userId: 'USR-ENG-02',
      userName: 'Marcus Vance',
      role: 'ENGINEER',
      action: 'SIMULATION_EXECUTED',
      resourceType: 'SimulationRun',
      resourceId: 'SIM-RUN-01',
      details: 'Executed what-if overdrive scenario simulation on MT-001',
      status: 'SUCCESS',
      ipAddress: '192.168.10.58',
    },
  ];

  // Helper methods
  public getMachine(id: string): Machine | undefined {
    return this.machines.find(m => m.id === id);
  }

  public logAction(
    userId: string,
    action: string,
    resourceType: string,
    resourceId: string,
    details: string,
    status: 'SUCCESS' | 'DENIED' | 'FAILED' = 'SUCCESS',
    ipAddress = '127.0.0.1'
  ) {
    const user = this.users.find(u => u.id === userId) || this.users[0];
    const log: AuditLog = {
      id: `AUD-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
      timestamp: new Date().toISOString(),
      userId: user.id,
      userName: user.name,
      role: user.role,
      action,
      resourceType,
      resourceId,
      details,
      status,
      ipAddress,
    };
    this.auditLogs.unshift(log);
    if (this.auditLogs.length > 500) {
      this.auditLogs.pop();
    }
  }
}

export const db = new RelationalDatabase();
